### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by ztjevan** [dploeger/zimbra.de_dieploegers_groupcal#8]
Dear Sir,
When I try to run this script : /usr/local/sbin/groupcal-run.sh  
some error will show :
Traceback (most recent call last):
  File "/usr/local/sbin/groupcal.py", line 240, in <module>
    c.execute("DROP TABLE IF EXISTS APPTCACHE")
sqlite3.OperationalError: database is locked

Is there any solution to fix it ?

**Comment by ztjevan** [comment]
and here is another message in the mailbox log"
##################
2018-07-19 10:31:04,568 WARN  [qtp1632392469-52061:http://test.zimbra.ltd/service/soap/GetTimespanRequest] [name=test@test.zimbra.ltd;mid=8;ip=xxx.xxx.xxx.xxx;port=58354;ua=ZimbraWebClient - GC67 (Win)/8.7.4_GA_1730;] SoapEngine - handler exception
com.zimbra.common.service.ServiceException: No data available.
ExceptionId:qtp1632392469-52061:http://test.zimbra.ltd/service/soap/GetTimespanRequest:1531967464568:e32ae3ec60fcbbf5
Code:service.NOT_FOUND
	at com.zimbra.common.service.ServiceException.NOT_FOUND(ServiceException.java:414)
	at de.dieploegers.groupcal.handlers.GetTimespan.handle(GetTimespan.java:86)
	at com.zimbra.soap.SoapEngine.dispatchRequest(SoapEngine.java:607)
	at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:460)
	at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:273)
	at com.zimbra.soap.SoapServlet.doWork(SoapServlet.java:303)
	at com.zimbra.soap.SoapServlet.doPost(SoapServlet.java:213)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at com.zimbra.cs.servlet.ZimbraServlet.service(ZimbraServlet.java:206)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at com.zimbra.cs.servlet.CsrfFilter.doFilter(CsrfFilter.java:169)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.zimbra.cs.servlet.RequestStringFilter.doFilter(RequestStringFilter.java:54)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:59)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.zimbra.cs.servlet.ETagHeaderFilter.doFilter(ETagHeaderFilter.java:47)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.zimbra.cs.servlet.ContextPathBasedThreadPoolBalancerFilter.doFilter(ContextPathBasedThreadPoolBalancerFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter(ZimbraQoSFilter.java:116)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.zimbra.cs.servlet.ZimbraInvalidLoginFilter.doFilter(ZimbraInvalidLoginFilter.java:117)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:473)
	at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:318)
	at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:288)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:318)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:437)
	at org.eclipse.jetty.server.handler.DebugHandler.handle(DebugHandler.java:84)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
################
and I put another user in the sec_gal distribution, and when the user login the system, it will show him some error
![20180719103233](https://user-images.githubusercontent.com/10355631/42918194-5d1defe0-8b3f-11e8-9cbd-3ead58710a39.png)

**Comment by ghost** [comment]
Did you try adding a few appointments in any of the shared calendars?

I have seen the locking issue as well, seems maybe sqlite was not the best option for these type of work.

What is the result of 
ls -hal /opt/zimbra/data/caching.db
?

**Comment by ztjevan** [comment]
@barrydegraaff 
ls -hal /opt/zimbra/data/caching.db
-rw-r----- 1 zimbra zimbra 3.0K Jul 20 08:30 /opt/zimbra/data/caching.db
################################
I just set it up. and login the calendar admin account . and add a appointments in it.
because this account is in both gal and sec_gal distribution , so I logout and login again to test it.

And Do I need to share the calendar to other?

################################
Did I do something wrong or did I miss some step?

**Comment by ztjevan** [comment]
and when I try to run the command in the groupcal-run.sh by myself.
/usr/bin/python2 /usr/local/sbin/groupcal.py -D /opt/zimbra/data/caching.db test.zimbra.ltd groupcaladmin@test.zimbra.ltd Password
return a error:
ERROR:root:Cannot login into zimbra with the supplied credentials.

Is this correct?

**Comment by ghost** [comment]
Did you change the password of the admin account generated by the installer?

Re-download and re-run the installer please.

**Comment by ghost** [comment]
@ztjevan would you be willing to support the project with a donation, so we can move it to Python3 and support MariaDB instead of SQLite?

**Comment by ztjevan** [comment]
@barrydegraaff Sorry for so late to reply because of the weekend. and do you have a email account ?

**Comment by ghost** [comment]
No worries, info@barrydegraaff.tk

**Comment by kcepaxe** [comment]
I have the same problem. I have sql3lite locked database and wrong zinlet description in new centos 7 zimbra installation. Can you help me please? my email: kcepaxe@gmail.com

**Comment by ghost** [comment]
fixed, we replaced sqlite with maridb
